name: Deploy to Custom Domain

# Trigger the workflow on push to the main branch
on:
  push:
    branches: ["main"]

# Define the jobs for the workflow
jobs:
  # Job for building and deploying the Vite app
  deploy-vite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  # Job for deploying to your server using SSH
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            # Navigate to the server project directory
            cd /var/www/portfolio-ThreeJS

            # Pull the latest changes from the Git repository
            git pull origin main

            # Display the current Git status (optional)
            git status

            # Install dependencies and build your project
            npm install
            npm update
            npm run build

  # Combine the two workflows
  # Run the Vite deployment first and then deploy to the server
  # You may need to adjust this based on your specific requirements
  deploy:
    runs-on: ubuntu-latest
    needs: [deploy-vite, deploy-server]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"

      # Add more steps here if needed for your deployment process
      # For example, you might want to copy artifacts from the Vite build to the server
# Add more steps here if needed for your deployment process
# For example, you might want to copy artifacts from the Vite build to the server
